#!/usr/env/bin bash
tmux_pid=$(pgrep -P$1 tmux)
session_name=$(grep -zFxA1 -- '-s' < /proc/$tmux_pid/cmdline | cut -b3-)

tmux neww -t $session_name "$(cat <<EOF
    $EDITOR $2;
    tmux loadb $2 \; pasteb -t $session_name:-1 ;
    rm $2 ;
EOF
)"
