#!/usr/bin/env zsh

# send a notification when command completes
function alert {
    RVAL=$?                 # get return value of the last command
    DATE=`date +"%Y/%m/%d %H:%M:%S"` # get time of completion
    LAST=$history[$HISTCMD] # get current command
    LAST=${LAST%[;&|]*}     # remove "; alert" from it
    echo -ne "\e]2;$LAST\a" # set window title so we can get back to it
    LAST=${LAST//\"/'\"'}   # replace " for \" to not break lua format

    # check if awesome is present
    (( $+commands[somewm-client] )) || return

    # check if the command was successful
    if [[ $RVAL == 0 ]]; then
        RESULT="SUCCESS"
        BG_COLOR="#535d9a"
    else
        RESULT="FAILURE"
        BG_COLOR="#ba3624"
    fi

    # compose the notification
    COMMAND=$(tr -d '\n' <<EOF
require("naughty").notify({
title = "Command completed: \t${DATE}",
text = "Result: ${RESULT}\t\tExit code: ${RVAL}\n$ ${LAST}",
timeout = 0,
screen = 1,
bg = "${BG_COLOR}",
fg = "#ffffff",
margin = 8,
width = 600,
run = function () run_or_raise(nil, { name = "${LAST}" }) end
})
EOF
)
    # send it to somewm
    somewm-client eval "${COMMAND}" > /dev/null
}
