#!/usr/bin/env zsh

# Global
alias -g A='alert'
alias -g G='grep'
alias -g O='xdg-open'

alias ap='ansible-playbook -D'
alias bc='bc -q'
alias c='curl -sSL --fail-with-body'
alias cm='clipmenu'
alias dd='dd status=progress'
alias dt='date +"%Y%m%dT%H%M%S"'
alias dy='df --sync -hTt ext4'
alias flush='sync; sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"'
alias fucking='sudo'
alias grep='grep --color -i'
alias gv='gvim --remote-silent'
alias httpat='python2 -m SimpleHTTPServer'
alias invert='xcalib --invert --alter'
alias kt='du -h --max-depth=1 | sort -h'
alias livestreamer='livestreamer -p "mpv --cache=524288 --fs -"'
alias ll='ls -lh --color'
alias mm="make -j6"
alias n='sudo ss -lpsntu'
alias pr='enscript --no-job-header --pretty-print --color --landscape --borders --columns=2 --word-wrap --mark-wrapped=arrow '
alias qapt='sudo apt --quiet'
alias qupdate='sudo apt update && sudo apt upgrade'
alias restart='sudo rc-config restart '
alias rsync='rsync --partial --progress'
alias spot="fzf | tr '\n' '\0' | xargs -0 realpath | tee >(xclip -i -selection clipboard) >(xclip -i)"
alias ssh-unsafe='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias tt="tree -CdL 2"
alias uctl='systemctl --user'
alias wq='du -sh'
alias ytdl-audio='yt-dlp --add-metadata --extract-audio --format m4a --audio-format vorbis -o "%(autonumber)02d %(uploader)s - %(title)s (%(id)s).%(ext)s"'
alias chat='mkdir -p /tmp/opencode && nono run --workdir /tmp/opencode --profile opencode-local -- opencode'
alias opencode='nono run --allow-cwd --profile opencode-local -- opencode'
alias oc='opencode'

# Copying
alias copy='xclip -selection primary'
alias clip='xclip -selection clipboard'
alias paste='xclip -selection clipboard -o'

# wake up caspair
alias wakecaspair='wakeonlan d8:cb:8a:31:9d:5e'
alias wakemelchior='wakeonlan 00:1b:21:06:f1:cc'
alias wakelilim='wakeonlan 8c:16:45:3c:7d:15'

# CapsLock hell escape
alias CAPSLOCKOFF='xkbset nullify lock'
alias CAPSOFF='xkbset nullify lock'
