#!/usr/bin/env zsh

if [ -n "${commands[fzf-share]}" ]; then
    # This is available on NixOS
    source $(fzf-share)/completion.zsh
    source $(fzf-share)/key-bindings.zsh
elif [[ -f ~/.fzf.zsh ]]; then
    source ~/.fzf.zsh
fi
bindkey '^F' fzf-cd-widget
