#!/usr/bin/env zsh

function fzf-rootly-alerts {
    local help=$(echo -e "\033[2;37menter: Show alert | ctrl+r : Refresh | ctrl+o : Open in browser | ctrl+a : Acknowledge | ctrl+f : Resolve | ctrl+t : Triggered\033[0m")
    local refresh='reload-sync(rootly-alerts-table)+refresh-preview'
    local selected=$(
        rootly-alerts-table | fzf \
            --ansi \
            --with-shell 'zsh -fc' \
            --query="${LBUFFER:-}" \
            --header="${help}" \
            --header-lines=1 \
            --preview-window='bottom:26:wrap' \
            --preview='script -q /dev/null -c "rootly alerts get --format=table {1}"' \
            --bind="ctrl-r:${refresh}" \
            --bind="ctrl-o:execute-silent(xdg-open https://rootly.com/account/alerts/{1})" \
            --bind="ctrl-a:execute(rootly alerts ack {1})+${refresh}" \
            --bind="ctrl-f:execute(rootly alerts resolve {1})+${refresh}" \
            --bind="ctrl-t:execute(rootly alerts update --status=triggered {1})+${refresh}"
    )

    [ -z "${selected}" ] && return

    local alert_id="${selected%% *}"

    BUFFER="rootly alerts get ${alert_id}"

    if [ -z "${ZLE_STATE}" ]; then
        echo "${selected}"
        echo
        eval "${BUFFER}"
    else
        zle accept-line
        zle reset-prompt
    fi
}

zle -N fzf-rootly-alerts
bindkey '^x' fzf-vault
