#!/usr/bin/env zsh

# change color based on vimode
zle-keymap-select () {
    if [ $KEYMAP = vicmd ]; then
        echo -ne "\033]12;Red\007"
    else
        echo -ne "\033]12;White\007"
    fi
}

zle-line-finish () {
    zle -K viins
    echo -ne "\033]12;White\007"
}

zle-line-init () {
    zle -K viins
    echo -ne "\033]12;White\007"
}

# use these only if terminal is graphical
if [[ $TERM != "linux" ]]; then
    zle -N zle-keymap-select
    zle -N zle-line-finish
    zle -N zle-line-init
fi

