return {
  { "LaTeX-Box-Team/LaTeX-Box", ft = "latex" },
  { "LnL7/vim-nix", ft = "nix" },
  { "NoahTheDuke/vim-just", ft = "just" },
  { "bfredl/nvim-ipy", ft = "python" },
  { "fatih/vim-go", ft = "go" },
  { "hashivim/vim-terraform", ft = "terraform" },
  { "hynek/vim-python-pep8-indent", ft = "python" },
  { "lepture/vim-jinja", ft = "jinja" },
  { "martinda/Jenkinsfile-vim-syntax", ft = "Jenkinsfile" },
  { "moll/vim-node", ft = "javascript" },
  { "nfnty/vim-nftables", ft = "nft" },
  { "pangloss/vim-javascript", ft = "javascript" },
  { "pearofducks/ansible-vim", ft = "ansible" },
  { "robbles/logstash.vim", ft = "logstash" },
  { "sebdah/vim-delve", ft = "go" },
  { "tell-k/vim-autopep8", ft = "python" },
  { "zah/nim.vim", ft = "nim" },
  { "hjson/vim-hjson", ft = "hujson" },
}
